### ISSUE TITLE
Missing fakeroot should be a fatal error, not a warning

### ISSUE THREAD

**Issue by ardovm** [jimjag/epm#1]
Hello,

following [OpenOffice bug 128413](https://bz.apache.org/ooo/show_bug.cgi?id=128413) I would like to suggest that if `epm` is unable to ensure the file permissions in a generated Debian archive, it should consider it a fatal error rather than a warning.

Apparently, epm _can_ predict in advance whether the permissions will be respected or not, because the warning seems to disappear when the condition are met.

If you agree on this, and you do not have time do dedicate to it, I can look into the code and prepare a pull request.

**Comment by jimjag** [comment]
Not sure if I agree. I think a warning is warranted, since it allows the end=user to either ignore it or fix it after the fact.
